export const MENU = [
  {
    id: 0,
    name: 'Americano',
    price: 5.99,
    rating: 4.9,
    imgSrc: './img/menu/Americano.jpg',
    hotDrink: true,
    desert: true,
  },
  {
    id: 1,
    name: 'Cappuccino',
    price: 4.59,
    rating: 4.4,
    imgSrc: './img/menu/cappuccino-005.webp',
    hotDrink: true,
    desert: true,
  },
  {
    id: 2,
    name: 'Espresso',
    price: 3.59,
    rating: 4.4,
    imgSrc: './img/menu/espresso.jpg',
    hotDrink: true,
    desert: true,
  },
  {
    id: 3,
    name: 'Chocolate Truffle and Honeycomb Torte',
    price: 8.0,
    rating: 4.9,
    imgSrc: './img/menu/Chocolate-truffle-and-honeycomb-torte-40ac4e3.webp',
    hotDrink: true,
    desert: true,
  },
  {
    id: 4,
    name: 'Double Chocolate Chip Frappe',
    price: 6.59,
    rating: 4.4,
    imgSrc: './img/menu/double-Chocolate-Chip-Frappe-2-3.jpg',
    hotDrink: true,
    desert: true,
  },
  {
    id: 5,
    name: 'Chocolate Molten Cakes',
    price: 8.99,
    rating: 4.4,
    imgSrc: './img/menu/easy-chocolate-molten-cakes-37a25eb.webp',
    hotDrink: true,
    desert: true,
  },
  {
    id: 6,
    name: 'Floating Island',
    price: 7.99,
    rating: 4.9,
    imgSrc: './img/menu/floating-island-3a8b98b.webp',
    hotDrink: true,
    desert: true,
  },
  {
    id: 7,
    name: 'Iced Americano',
    price: 3.59,
    rating: 4.0,
    imgSrc: './img/menu/iced american.jpg',
    hotDrink: true,
    desert: true,
  },
  {
    id: 8,
    name: 'Latte',
    price: 2.59,
    rating: 4.4,
    imgSrc: './img/menu/latte.jpg',
    hotDrink: true,
    desert: true,
  },
  {
    id: 9,
    name: 'Mocha Frappe',
    price: 4.49,
    rating: 3.9,
    imgSrc: './img/menu/mocha-frappe.jpg',
    hotDrink: true,
    desert: true,
  },
  {
    id: 10,
    name: 'Mochaccino',
    price: 4.59,
    rating: 4.4,
    imgSrc: './img/menu/Mochaccino.webp',
    hotDrink: true,
    desert: true,
  },
  {
    id: 11,
    name: 'Salted Chocolate Hazelnut Brownies',
    price: 4.59,
    rating: 4.4,
    imgSrc: './img/menu/salted-chocolate-hazelnut-brownies-250693d.webp',
    hotDrink: true,
    desert: true,
  },
];
